steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build --build-arg API_KEY=$_API_KEY -t gcr.io/$PROJECT_ID/designers-toolkit .
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/designers-toolkit']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'designers-toolkit'
      - '--image'
      - 'gcr.io/$PROJECT_ID/designers-toolkit'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/designers-toolkit'
substitutions:
  _API_KEY: '' # User should set this in Cloud Build triggers
